# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'
  
- task: npmAuthenticate@0
  inputs:
    workingFile: '.npmrc'
    customEndpoint: 'npm'  

- script: |
    npm install -g @angular/cli
    npm install scss-bundle -g
    npm install        
  displayName: 'Install'
  continueOnError: false
  failOnStderr: true
  
- script: |
    ng test openpos-client-core-lib
  displayName: 'Test'    
  continueOnError: true
  failOnStderr: false

- task: PublishTestResults@2
  displayName: 'Publish Test Results'    
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '**/TESTS.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    failTaskOnFailedTests: true # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional      

    
- script: |    
    ng build openpos-client-core-lib
    scss-bundle -c projects/openpos-client-core-lib/scss-bundle.config.json
  displayName: 'Build'
  continueOnError: false
  failOnStderr: false


- script: |
    npm install -g publish-if-not-published
    cp .npmrc dist/openpos-client-core-lib
    cd dist/openpos-client-core-lib
    publish-if-not-published
    npm pack
    mv jumpmind-openpos-client-core-lib-*.tgz jumpmind-openpos-client-core-lib-snapshot.tgz
  displayName: 'Publish if not already published'
  
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: maven.jumpmind.com
    #sourceFolder: # Optional
    contents: '**/jumpmind-openpos-client-core-lib-snapshot.tgz' 
    targetFolder: 'www/npm' # Optional
    cleanTargetFolder: true # Optional
    overwrite: true # Optional
    failOnEmptySource: true # Optional
    flattenFolders: true # Optional    
    #publishRunAttachments: true # Optional   
