resources:
  - name: openposFrameworkGit
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: JumpMindGitHub
      # Repository path, including org name/repo name
      path: JumpMind/openpos-framework
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

pipelines:
  - name: gradleBuildPipeline
    steps:
      - name: gradleBuildStep
        type: GradleBuild
        configuration:
          runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - "10.21.0"
          gradleCommand: "build -PdownloadNode=true"
          sourceLocation: openpos-assemble
          deployerRepo: default-maven-local
          useWrapper: true
          inputSteps:
            - name: installChrome
          integrations:
            - name: JumpMindArtifactory
