pipelines:
  - name: gradleBuildPipeline
    steps:
      - name: gradleBuildStep
        type: GradleBuild
        configuration:
          gradleCommand: "build"
          sourceLocation: openpos-assemble
          deployerRepo: default-maven-local
          useWrapper: true
          inputResources:
            - name: JumpMindGitHub
          integrations:
            - name: JumpMindArtifactory
