resources:
  - name: openposFrameworkGit
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: JumpMindGitHub
      # Repository path, including org name/repo name
      path: JumpMind/openpos-framework
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

pipelines:
  - name: gradleBuildPipeline
    steps:
      - name: installChrome
        type: Bash
        configuration:
          inputResources:
            - name: openposFrameworkGit
        execution:
            onExecute:
              - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
              - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
              - apt-get clean
              - apt-get update
              - apt-get install -y google-chrome-stable xvfb
      - name: gradleBuildStep
        type: GradleBuild
        configuration:
          gradleCommand: "build -PdownloadNode=true"
          sourceLocation: openpos-assemble
          deployerRepo: default-maven-local
          useWrapper: true
          inputSteps:
            - name: installChrome
          inputResources:
            - name: openposFrameworkGit
          integrations:
            - name: JumpMindArtifactory
