resources:
  - name: openposFrameworkGit
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: JumpMindGitHub
      # Repository path, including org name/repo name
      path: openpos-framework
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

pipelines:
  - name: gradleBuildPipeline
    steps:
      - name: gradleBuildStep
        type: GradleBuild
        configuration:
          gradleCommand: "build"
          sourceLocation: openpos-assemble
          deployerRepo: default-maven-local
          useWrapper: true
          inputResources:
            - name: openposFrameworkGit
          integrations:
            - name: JumpMindArtifactory
